[package]
name = "compiler-impl"
version = "0.1.0"
authors = ["Rob Jenks <robjenks@gmail.com>"]
edition = "2018"


[dependencies]
common = { path = "src/common" }
lexer = { path = "src/lexer" }
parser = { path = "src/parser" }

itertools = "0.8.2"
log = "0.4.8"
env_logger = "0.7.1"
